# Generated by Django 4.0.6 on 2022-08-10 00:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='trabajo',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'ABOGADO'), ('4', 'INGENIERO'), ('5', 'OTRO')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
